library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(httr)
library(XML)
library(stringr)
library(tidyverse)
library(sp)
library(rgdal)
library(raster)
library(rgeos)
library(cluster)
library(scales)
options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")

